import Head from 'next/head';
import Image from 'next/image';

export default function CaptainAmericaPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl hover:text-teal-400 transition">
          Tailwind
        </h1>
        <div className="img-container">
          <Image
            src="https://cdn.britannica.com/30/182830-050-96F2ED76/Chris-Evans-title-character-Joe-Johnston-Captain.jpg"
            alt="Vercel Logo"
            // width={100}
            // height={100}
            priority
            fill
          />
        </div>
      </main>
    </>
  );
}
